export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptLinkedInInsight, useScriptCalendly, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useKutoBreadcrumb } from '../app/composables/useKutoBreadcrumb';
export { useKutoMobileNav } from '../app/composables/useKutoMobileNav';
export { useKutoPagination } from '../app/composables/useKutoPagination';
export { kutoContactRoleBadgeClass, kutoContactStatusBadgeClass } from '../app/utils/kutoContactBadges';
export { kutoContactHistoryStatusBadgeClass, kutoContactHistoryTypeColor } from '../app/utils/kutoContactHistoryBadges';
export { kutoCustomerTierBadgeClass, kutoCustomerTypeBadgeClass, kutoCustomerRenewalBadgeClass, kutoCustomerHealthColor } from '../app/utils/kutoCustomerBadges';
export { kutoLeadStatusBadgeClass, kutoLeadPriorityBadgeClass, kutoLeadSourceBadgeClass } from '../app/utils/kutoLeadBadges';
export { useSupabaseClient } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.2/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseClient';
export { useSupabaseCookieRedirect } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.2/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseCookieRedirect';
export { useSupabaseSession } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.2/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseSession';
export { useSupabaseUser } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.2/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseUser';
export { defineLocale, extendLocale } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/defineLocale';
export { defineShortcuts, extractShortcuts } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts';
export { useContentSearch } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch';
export { useFileUpload } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload';
export { useFormField } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useFormField';
export { useKbd } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useKbd';
export { useOverlay } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useOverlay';
export { useResizable } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useResizable';
export { useScrollShadow } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow';
export { useScrollspy } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy';
export { useToast } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useToast';
export { useTour } from '../node_modules/.pnpm/@nuxt+ui@4.9.0_14a9fb73fa2fbca3f237ec7ac9ddcc4e/node_modules/@nuxt/ui/dist/runtime/composables/useTour';
export { useI18n } from '../node_modules/.pnpm/vue-i18n@10.0.8_vue@3.5.38_typescript@6.0.3_/node_modules/vue-i18n/dist/vue-i18n';
export { useRouteBaseName, useLocalePath, useLocaleRoute, useSwitchLocalePath, useLocaleHead, useBrowserLocale, useCookieLocale, useSetI18nParams, defineI18nRoute, defineI18nLocale, defineI18nConfig } from '../node_modules/.pnpm/@nuxtjs+i18n@9.5.6_@vue+compiler-dom@3.5.38_eslint@10.5.0_jiti@2.7.0__magicast@0.5.3_ro_9ef4a0c5262276e6e6ac0effad8b3182/node_modules/@nuxtjs/i18n/dist/runtime/composables/index';
export { useNuxtDevTools } from '../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.5_jiti@2.7.0_lightningcss@1.32.0_terser@5.48.0_yaml@2.9.0__vue@3.5.38_typescript@6.0.3_/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';
export { useColorMode } from '../node_modules/.pnpm/@nuxtjs+color-mode@4.0.1_magicast@0.5.3/node_modules/@nuxtjs/color-mode/dist/runtime/composables';