/** ไอคอนเมนูย่อย sidebar — ตรง figma.site (lucide) · key = `parentKey.childKey` */
export const kutoNavSubIcons: Record<string, string> = {
  // leads — ดู kutoMenu.ts (กำหนดใน node โดยตรง)

  'customers.list': 'i-lucide-list',
  'customers.contacts': 'i-lucide-users',
  'customers.contactHistory': 'i-lucide-history',
  'customers.c360': 'i-lucide-scan',
  'customers.accounts': 'i-lucide-briefcase',
  'customers.documents': 'i-lucide-file-text',
  'customers.branches': 'i-lucide-git-branch',
  'customers.duplicates': 'i-lucide-copy',
  'customers.import': 'i-lucide-upload',
  'customers.activitySchedule': 'i-lucide-calendar-clock',

  'contacts.list': 'i-lucide-list',
  'contacts.primary': 'i-lucide-star',
  'contacts.decisionMakers': 'i-lucide-crown',
  'contacts.purchasing': 'i-lucide-shopping-cart',
  'contacts.it': 'i-lucide-monitor',
  'contacts.roles': 'i-lucide-badge-check',
  'contacts.history': 'i-lucide-history',
  'contacts.duplicates': 'i-lucide-copy',
  'contacts.import': 'i-lucide-upload',
  'contacts.schedule': 'i-lucide-calendar',

  'opportunities.pipelineKanban': 'i-lucide-kanban',
  'opportunities.list': 'i-lucide-list',
  'opportunities.new': 'i-lucide-plus-circle',
  'opportunities.mine': 'i-lucide-user',
  'opportunities.team': 'i-lucide-users',
  'opportunities.detail': 'i-lucide-file-search',
  'opportunities.forecast': 'i-lucide-trending-up',
  'opportunities.stale': 'i-lucide-clock',
  'opportunities.competitors': 'i-lucide-swords',
  'opportunities.winLoss': 'i-lucide-scale',
  'opportunities.lostReasons': 'i-lucide-circle-x',
  'opportunities.scoring': 'i-lucide-gauge',
  'opportunities.salesStages': 'i-lucide-git-merge',

  'quotations.list': 'i-lucide-list',
  'quotations.create': 'i-lucide-file-plus',
  'quotations.approvals': 'i-lucide-check-circle',
  'quotations.pricing': 'i-lucide-tags',
  'quotations.templates': 'i-lucide-layout-template',
  'quotations.versions': 'i-lucide-git-branch',
  'quotations.expired': 'i-lucide-calendar-x',

  'contracts.all': 'i-lucide-list',
  'contracts.renewalAlerts': 'i-lucide-bell',
  'contracts.renewalForecast': 'i-lucide-line-chart',
  'contracts.expiring': 'i-lucide-hourglass',
  'contracts.expired': 'i-lucide-calendar-off',
  'contracts.renewed': 'i-lucide-refresh-cw',
  'contracts.notRenewed': 'i-lucide-ban',
  'contracts.renewalCalendar': 'i-lucide-calendar',
  'contracts.m365': 'i-lucide-cloud',
  'contracts.google': 'i-lucide-mail',
  'contracts.firewall': 'i-lucide-shield',
  'contracts.edr': 'i-lucide-shield-alert',
  'contracts.maintenance': 'i-lucide-wrench',
  'contracts.sla': 'i-lucide-file-check',
  'contracts.warranty': 'i-lucide-award',

  'assets.all': 'i-lucide-list',
  'assets.installedBase': 'i-lucide-server',
  'assets.subscriptions': 'i-lucide-repeat',
  'assets.warranty': 'i-lucide-shield-check',
  'assets.byCustomer': 'i-lucide-building-2',
  'assets.import': 'i-lucide-upload',
  'assets.settings': 'i-lucide-settings-2',

  'tickets.all': 'i-lucide-list',
  'tickets.create': 'i-lucide-plus',
  'tickets.mine': 'i-lucide-user',
  'tickets.team': 'i-lucide-users',
  'tickets.kanban': 'i-lucide-kanban',
  'tickets.sla': 'i-lucide-timer',
  'tickets.engineerAssign': 'i-lucide-user-cog',
  'tickets.serviceReport': 'i-lucide-clipboard-list',
  'tickets.knowledgeBase': 'i-lucide-book-open',

  'activities.mine': 'i-lucide-user',
  'activities.schedule': 'i-lucide-calendar-days',
  'activities.calendar': 'i-lucide-calendar',
  'activities.meetings': 'i-lucide-video',
  'activities.followUp': 'i-lucide-phone-forwarded',

  'documents.all': 'i-lucide-files',
  'documents.customer': 'i-lucide-building-2',
  'documents.quotation': 'i-lucide-file-text',
  'documents.contract': 'i-lucide-file-signature',
  'documents.project': 'i-lucide-folder-kanban',
  'documents.service': 'i-lucide-clipboard-check',
  'documents.warranty': 'i-lucide-shield',
  'documents.invoice': 'i-lucide-receipt',
  'documents.templates': 'i-lucide-layout-template',
  'documents.versioning': 'i-lucide-git-branch',
  'documents.archived': 'i-lucide-archive',

  'settings.company': 'i-lucide-building',
  'settings.users': 'i-lucide-users',
  'settings.roles': 'i-lucide-shield',
  'settings.locale': 'i-lucide-languages',
  'settings.auditLog': 'i-lucide-scroll-text',
  'settings.teams': 'i-lucide-network',
  'settings.notifications': 'i-lucide-bell',
  'settings.approvalWorkflow': 'i-lucide-list-checks',
  'settings.security': 'i-lucide-lock',
  'settings.importExport': 'i-lucide-arrow-up-down',
  'settings.api': 'i-lucide-plug',
  'settings.masterData': 'i-lucide-database',
  'settings.aiSettings': 'i-lucide-bot',
  'settings.package': 'i-lucide-package',
  'settings.featureFlags': 'i-lucide-toggle-right',

  'settings.masterData.customerType': 'i-lucide-user',
  'settings.masterData.businessType': 'i-lucide-briefcase',
  'settings.masterData.leadSource': 'i-lucide-radar',
  'settings.masterData.salesStage': 'i-lucide-git-merge',
  'settings.masterData.productCategory': 'i-lucide-folder-tree',
  'settings.masterData.region': 'i-lucide-map-pin',
  'settings.masterData.tier': 'i-lucide-layers',
  'settings.masterData.unit': 'i-lucide-ruler',
  'settings.masterData.tags': 'i-lucide-tags',
  'settings.masterData.lostReason': 'i-lucide-circle-x'
}

export function kutoSubNavIcon(parentKey: string, childKey: string, nestedParent?: string): string | undefined {
  if (nestedParent) {
    return kutoNavSubIcons[`${nestedParent}.${parentKey}.${childKey}`]
      ?? kutoNavSubIcons[`${parentKey}.${childKey}`]
  }
  return kutoNavSubIcons[`${parentKey}.${childKey}`]
}
